export const images = [
  {
    id: 1,
    group: "About Andrew",
    src: "/radio.png",
    alt: "Gallery image 1",
    top: "-8%",
    left: "-8%",
    style: { width: "280px", height: "auto" },
  },
  {
    id: 2,
    group: "About Andrew",
    src: "/andy.png",
    alt: "Gallery image 2",
    top: "35%",
    left: "88%",
    style: { width: "250px", height: "auto" },
  },
  {
    id: 3,
    group: "Contact",
    src: "/business.png",
    alt: "Gallery image 3",
    top: "-12%",
    left: "45%",
    style: { width: "230px", height: "auto" },
  },
  {
    id: 4,
    group: "Projects and Awards",
    src: "/cal.png",
    alt: "Gallery image 4",
    top: "20%",
    left: "20%",
    style: { width: "250px", height: "auto" },
  },
  {
    id: 5,
    group: "Projects and Awards",
    src: "/sfsu.png",
    alt: "Gallery image 5",
    top: "70%",
    left: "72%",
    style: { width: "270px", height: "auto" },
  },
  {
    id: 6,
    group: "Experience",
    src: "/nasa.png",
    alt: "Gallery image 6",
    top: "60%",
    left: "45%",
    style: { width: "300px", height: "auto" },
  },
  {
    id: 7,
    group: "Experience",
    src: "/atoma-new.png",
    alt: "Gallery image 7",
    top: "10%",
    left: "40%",
    style: { width: "240px", height: "auto" },
  },
  {
    id: 8,
    group: "Involvement",
    src: "/hack.png",
    alt: "Gallery image 8",
    top: "-12%",
    left: "18%",
    style: { width: "260px", height: "auto" },
  },
  {
    id: 9,
    group: "Involvement",
    src: "/data-icon.png",
    alt: "Gallery image 9",
    top: "70%",
    left: "21%",
    style: { width: "190px", height: "auto" },
  },
  {
    id: 10,
    group: "Involvement",
    src: "/space-graphic.png",
    alt: "Gallery image 10",
    top: "13%",
    left: "60%",
    style: { width: "220px", height: "auto" },
  },
  {
    id: 11,
    group: "Skills",
    src: "/react.png",
    alt: "Gallery image 11",
    top: "45%",
    left: "-5%",
    style: { width: "200px", height: "auto" },
  },
  {
    id: 12,
    group: "Skills",
    src: "/python.png",
    alt: "Gallery image 12",
    top: "85%",
    left: "0%",
    style: { width: "240px", height: "auto" },
  },
  {
    id: 13,
    group: "Resume",
    src: "/resume.png",
    alt: "Gallery image 13",
    top: "-5%",
    left: "80%",
    style: { width: "230px", height: "auto" },
  },
];
