export const images = [
  {
    id: 1,
    group: "About Andrew",
    src: "/ok.jpeg",
    alt: "Gallery image 1",
    top: "30%",
    left: "5%",
    style: { width: "200px", height: "auto" },
  },
  {
    id: 2,
    group: "About Andrew",
    src: "/andrew1.jpg",
    alt: "Gallery image 2",
    top: "20%",
    left: "60%",
    style: { width: "200px", height: "auto" },
  },
  {
    id: 3,
    group: "Contact",
    src: "/business.png",
    alt: "Gallery image 3",
    top: "-2%",
    left: "40%",
    style: { width: "250px", height: "auto" },
  },
  {
    id: 4,
    group: "Projects and Awards",
    src: "/award2.png",
    alt: "Gallery image 4",
    top: "70%",
    left: "70%",
    style: { width: "150px", height: "auto" },
  },
  {
    id: 5,
    group: "Projects and Awards",
    src: "/awards.webp",
    alt: "Gallery image 5",
    top: "80%",
    left: "-5%",
    style: { width: "200px", height: "auto" },
  },
  {
    id: 6,
    group: "Experience",
    src: "/nasa.jpeg",
    alt: "Gallery image 6",
    top: "70%",
    left: "45%",
    style: { width: "250px", height: "auto" },
  },
  {
    id: 7,
    group: "Experience",
    src: "/atoma-circle.png",
    alt: "Gallery image 7",
    top: "20%",
    left: "25%",
    style: { width: "250px", height: "auto" },
  },
  {
    id: 8,
    group: "Involvement",
    src: "/hack.png",
    alt: "Gallery image 8",
    top: "-10%",
    left: "0%",
    style: { width: "150px", height: "auto" },
  },
  {
    id: 9,
    group: "Involvement",
    src: "/data-icon.png",
    alt: "Gallery image 9",
    top: "-8%",
    left: "20%",
    style: { width: "200px", height: "auto" },
  },
  {
    id: 10,
    group: "Involvement",
    src: "https://placehold.co/180x220",
    alt: "Gallery image 10",
    top: "-5%",
    left: "85%",
  },
  {
    id: 11,
    group: "Skills",
    src: "/js.png",
    alt: "Gallery image 11",
    top: "90%",
    left: "85%",
    style: { width: "220px", height: "auto" },
  },
  {
    id: 12,
    group: "Skills",
    src: "/python.png",
    alt: "Gallery image 12",
    top: "63%",
    left: "20%",
    style: { width: "250px", height: "auto" },
  },
  {
    id: 13,
    group: "Resume",
    src: "/resume.jpg",
    alt: "Gallery image 13",
    top: "30%",
    left: "80%",
    style: { width: "200px", height: "auto" },
  },
];
